feat: switch to google llm/embedding models, bump chunk size to 1000
OpenAI embeddings model has an issue that causes API requests to fail if using a larger chunk size:

```
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Requested 688696 tokens, max 300000 tokens per request', 'type': 'max_tokens_per_request', 'param': None, 'code': 'max_tokens_per_request'}}
```

By switching to google's gemini-embedding-001, we are able to bump the chunk size to 1000 chars. The chunk overlap was also increased from 120 to 200.

We also added a new "category" field to the document database to simplify the retrival procedure.